import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import {MessagesProvider} from "@/libs/context/MessagesContext";
import {ThemeCtxProvider} from "@/libs/context/ThemeContext";
import MessagesList from "@/app/components/Messages/MessagesList";
import NavBar from "@/app/components/NavBar/NavBar";
import ThemeWrapper from "@/app/components/Theme/ThemeWrapper/ThemeWrapper";
import "react-color-palette/css";
import {ReactNode} from "react";
import {Box} from "@mui/material";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AppRouterCacheProvider>
            <ThemeCtxProvider>
                <ThemeWrapper>
                    <MessagesProvider>
                        <Box component="div" sx={{display: 'flex', flexFlow: 'column', height: '100vh'}}>
                            <NavBar/>
                            <Box sx={{flex: 1}}>
                                <MessagesList/>
                                {children}
                            </Box>
                        </Box>
                    </MessagesProvider>
                </ThemeWrapper>
            </ThemeCtxProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
